# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacialRecognition' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Facial Recognition

  pod 'mailcore2-ios'

  # Pods for Google Calendar

  pod 'AppAuth'

end

workspace ‘FacialRecognition’